### ISSUE TITLE
Notification time delay a least for 2 hours.

### ISSUE THREAD

**Issue by Htet-Wai-Yan-HWY** [fozzle/observer-ward#14]
Hello,

Thanks for useful discord bot. But we have an issue with time.

As you can see player's match was over in 1:47 AM but the bot alert in the channel at 4:17 AM.

![Screenshot from 2024-05-12 04-49-35](https://github.com/fozzle/observer-ward/assets/100279699/c595a5b3-1e1e-446d-b586-d681997916e0)

![Screenshot from 2024-05-12 04-50-12](https://github.com/fozzle/observer-ward/assets/100279699/ede1bba1-2e0a-470f-9b6c-a4b3f65a05c8)

**Comment by fozzle** [comment]
I answered a similar query on reddit earlier:

> So sometimes the Dota2 match API goes down, or there are just too many matches being played, and the bot falls behind on processing matches. Right now it does seem rather behind.
> 
> Unfortunately I don't have a great way to catch back up without dropping old matches entirely, because Steam holds you to a tight rate limit of about 100 matches per 5s.
> 
> I think other platforms like OpenDota get around this by using multiple Steam API keys, but I was a bit hesitant to do the same because it seems...unsanctioned. And for the most part, once the bot catches up, it stays up to date until another outage happens.
> 
> I'll think about how to work around this some more because it's happened a few times lately.

**Comment by Htet-Wai-Yan-HWY** [comment]
Thanks, for the fast reply. 

Happy to use this discord bot.
